[package]
name = "dhall"
version = "0.1.0"
authors = ["NanoTech <nanotech@nanotechcorp.net>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.14.0"

[dependencies]
bytecount = "0.3.1"
lalrpop-util = "0.14.0"
nom = "3.2.0"
term-painter = "0.2.4"
